
#ifndef MESH2DN_HPP_
#define MESH2DN_HPP_

#include "dataStruct2D.hpp"
#include "GenericMesh.hpp"
#include <cstdlib>


class Mesh2 : public GenericMesh<Triangle2,BoundaryEdge2,Vertex2>
{
public:
  Mesh2() : GenericMesh<Triangle2,BoundaryEdge2,Vertex2>(){}
  Mesh2(const char *);                              // build from mesh generated by Freefem
  Mesh2(int nx, int ny, R orx, R ory, R lx, R ly);  // build structured mesh
  void init(int nx, int ny, R orx, R ory, R lx, R ly);  // build structured mesh

private:
  Mesh2(const Mesh2 &);                             // no copy constructor
  void operator=(const Mesh2 &);                    // no copy allowed
};


class MeshQuad2 : public GenericMesh<Quad2,BoundaryEdge2,Vertex2>
{
public:
  MeshQuad2(int nx, int ny, R orx, R ory, R lx, R ly);  // build structured mesh


private:
  MeshQuad2(const MeshQuad2 &);                             // no copy constructor
  void operator=(const MeshQuad2 &);                    // no copy allowed
};



#endif
